/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    BasicLayout: (typeof import("./src/components/basic-layout/index.vue"))["default"];
    CustomNavbar: (typeof import("./src/components/custom-navbar/index.vue"))["default"];
    Duihua: (typeof import("./src/components/iconfont/Duihua.vue"))["default"];
    Fabu: (typeof import("./src/components/iconfont/Fabu.vue"))["default"];
    Index: (typeof import("./src/components/iconfont/Index.vue"))["default"];
    NutButton: (typeof import("@nutui/nutui-taro"))["Button"];
    NutConfigProvider: (typeof import("@nutui/nutui-taro"))["ConfigProvider"];
    NutNavbar: (typeof import("@nutui/nutui-taro"))["Navbar"];
    NutTabbar: (typeof import("@nutui/nutui-taro"))["Tabbar"];
    NutTabbarItem: (typeof import("@nutui/nutui-taro"))["TabbarItem"];
    Redu: (typeof import("./src/components/iconfont/Redu.vue"))["default"];
    Xingqiu: (typeof import("./src/components/iconfont/Xingqiu.vue"))["default"];
    Yonghu: (typeof import("./src/components/iconfont/Yonghu.vue"))["default"];
  }
}
